export const BOOK_LIST_REQUEST = 'BOOK_LIST_REQUEST';
export const BOOK_LIST_SUCCESS = 'BOOK_LIST_SUCCESS';
export const BOOK_LIST_FAIL = 'BOOK_LIST_FAIL';

export const BOOK_DETAILS_REQUEST = 'BOOK_DETAILS_REQUEST';
export const BOOK_DETAILS_SUCCESS = 'BOOK_DETAILS_SUCCESS';
export const BOOK_DETAILS_FAIL = 'BOOK_DETAILS_FAIL';

export const BOOK_CREATE_REVIEW_REQUEST = 'BOOK_CREATE_REVIEW_REQUEST';
export const BOOK_CREATE_REVIEW_SUCCESS = 'BOOK_CREATE_REVIEW_SUCCESS';
export const BOOK_CREATE_REVIEW_FAIL = 'BOOK_CREATE_REVIEW_FAIL';
export const BOOK_CREATE_REVIEW_RESET = 'BOOK_CREATE_REVIEW_RESET';

export const BOOK_TOP_REQUEST = 'BOOK_TOP_REQUEST';
export const BOOK_TOP_SUCCESS = 'BOOK_TOP_SUCCESS';
export const BOOK_TOP_FAIL = 'BOOK_TOP_FAIL';

export const BOOK_SALE_REQUEST = 'BOOK_SALE_REQUEST';
export const BOOK_SALE_SUCCESS = 'BOOK_SALE_SUCCESS';
export const BOOK_SALE_FAIL = 'BOOK_SALE_FAIL';

export const BOOK_RELEASE_REQUEST = 'BOOK_RELEASE_REQUEST';
export const BOOK_RELEASE_SUCCESS = 'BOOK_RELEASE_SUCCESS';
export const BOOK_RELEASE_FAIL = 'BOOK_RELEASE_FAIL'