export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const POST_LIST_FAIL = 'POST_LIST_FAIL';

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST';
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS';
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL';

export const POST_CREATE_COMMENT_REQUEST = 'POST_CREATE_COMMENT_REQUEST';
export const POST_CREATE_COMMENT_SUCCESS = 'POST_CREATE_COMMENT_SUCCESS';
export const POST_CREATE_COMMENT_FAIL = 'POST_CREATE_COMMENT_FAIL';
export const POST_CREATE_COMMENT_RESET = 'POST_CREATE_COMMENT_RESET';

export const POST_TOP_REQUEST = 'POST_TOP_REQUEST';
export const POST_TOP_SUCCESS = 'POST_TOP_SUCCESS';
export const POST_TOP_FAIL = 'POST_TOP_FAIL';